version: "3.1"

services:
    app:
        build: ./app/
        container_name: jardinez_api
        env_file: .env
        ports: 
            - "8080:3000"
        environment: 
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PORT: ${DB_PORT}
            DB_HOST: ${DB_HOST}
    postgres:
        image: postgres:latest
        container_name: jardin_db
        env_file: .env
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes: 
            - ./db/data:/var/lib/postgresql/data
            - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        restart: always
